# Scripts to test API using VS Code Rest Client

@baseApiAddress = http://localhost:5000
@authRoute = auth
@collectionRoute = collection
@gamesRoute = games
@contentType = application/json

## Get JWT Token
# @name jwt
POST {{baseApiAddress}}/{{authRoute}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

userName=harry
&password=hedwig

###

# userName=hermione
# &password=crookshanks



##########################################################
# Happy path tests
##########################################################

# Get Games for User
GET {{baseApiAddress}}/{{collectionRoute}} HTTP/1.1
Authorization: Bearer {{jwt.response.body.value}}
Content-Type: {{contentType}}

###

# Add Game for User
## Example: Game Id 2 (Doom) to Harry
POST {{baseApiAddress}}/{{collectionRoute}} HTTP/1.1
Authorization: Bearer {{jwt.response.body.value}}
Content-Type: {{contentType}}

{
    "gameId": 5
}

###

# Delete game for user
## Example: Game Id 2 (Doom) for Harry
@gameId = 5
DELETE {{baseApiAddress}}/{{collectionRoute}}/{{gameId}}
content-type: application/json
Authorization: Bearer {{jwt.response.body.value}}

###

# Add Game
## Example: Add Halo 2 with Microsoft as Publisher 
##          and Adventure,Digital,Science Fiction as Genres
POST {{baseApiAddress}}/{{gamesRoute}}
content-type: application/json
Authorization: Bearer {{jwt.response.body.value}}

{
    "name": "Halo2",
    "releaseDate": "2004-11-09",
    "overview": "Halo 2 is a 2004 first-person shooter game developed by Bungie and published by Microsoft Game Studios. Released for the Xbox, the game is the second installment in the Halo franchise and the sequel to 2001's critically acclaimed Halo: Combat Evolved.",
    "publisherId": 1,
    "genreIds": [2,9,10]
}

###

# Add Game
## Example 2: Add Halo 4 with Microsoft as Publisher 
##          and Adventure,Digital,Science Fiction as Genres
POST {{baseApiAddress}}/{{gamesRoute}}
content-type: application/json
Authorization: Bearer {{jwt.response.body.value}}

{
    "name": "Halo4",
    "releaseDate": "2012-11-06",
    "overview": "Halo 4 is a first-person shooter developed by 343 Industries and published by Microsoft Studios for the Xbox 360 video game console. The fourth mainline installment and seventh overall in the Halo franchise, the game was released on November 6, 2012",
    "publisherId": 1,
    "genreIds": [2,9,10]
}

###